XBE_TITLE = nxdyn_test
GEN_XISO = $(XBE_TITLE).iso
SRCS = $(CURDIR)/src/main.c

CFLAGS += -Iinclude -I../../nxdll/nxdll_loader/include
LDFLAGS += ../../nxdll/target/i386-xbox-win32/release/libnxdll_loader.a

include $(NXDK_DIR)/Makefile
